spring:
  profiles:
    active: local
    group:
      local: common, secret
      prod1: common, prod1-server, secret
      prod2: common, prod2-server, secret

server:
  env: blue

---

spring:
  config:
    activate:
      on-profile: common
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: 2dc5c2ec61e5efeb6b952c1b5d381821
            redirectUri: http://3.36.41.19/login/oauth2/code/kakao
            authorizationGrantType: authorization_code
            clientAuthenticationMethod: POST
            clientName: Kakao
          naver:
            clientId: i4eW_RUc74M3Ci96bJuG
            redirectUri: http://3.36.41.19/login/oauth2/code/naver
            authorizationGrantType: authorization_code
            clientAuthenticationMethod: POST
            clientName: Naver
        provider:
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response

mybatis:
  mapper-locations:
    - /mappers/*.xml

serverName: common

---

spring:
  config:
    activate:
      on-profile: prod1-server

server:
  port: 8080

serverName: prod1-server

---

spring:
  config:
    activate:
      on-profile: prod2-server

server:
  port: 8081

serverName: prod2-server

